SE-8 filters
polyse/database pull request #2
Opened 2020-04-30 12:53 UTC by TarIvAl

https://polisgo2020.atlassian.net/browse/SE-8?atlOrigin=eyJpIjoiMjBjYjhjODUxNGY1NGIyNmEzNDE3NzdkZDFiNzg2YzMiLCJwIjoiaiJ9

Не уверен, что модули сделал в том виде как задумывалось.

2020-04-30 13:51 UTC, K1ta commented
Мне кажется, у тебя как то слишком сильно на модули разбито, плюс нет конкретного интерфейса для всех фильтров. Мб сделать что-нибудь вроде такого?

```
type Filter interface {
	Apply(word string) string
}
```
Тогда разделение текста на токены сделать отдельной функцией, которая принимает на вход список фильтров, например:
```
func FilterText(text string, filters ...Filter) []string {
	words := strings.Fields(text)
	for i := range words {
		for j := range filters {
			words[i] = filters[j].Apply(words[i])
		}
	}
	return words
}
```

2020-04-30 13:59 UTC, senyasdt reviewed
В общем и целом я согласен с @K1ta но я бы сделал сигнатуру примерно вот такой

```go
type WFilter interface{
    Handle(tokens ... string) []string
}
```

Просто apply фильтра к каждому слову... Не знаю
Про `FilterText` пока что солидарен потому что ничего лучше не придумал

2020-04-30 14:05 UTC, senyast4745 commented
Сори за миллион комментов, GitHub лагает

2020-04-30 14:07 UTC, senyasdt reviewed
Остальные файлы посмотрел

2020-04-30 14:18 UTC, K1ta commented
> Просто apply фильтра к каждому слову... Не знаю
@senyast4745, я просто хотел уйти от цикла в каждом фильтре. Хотя, без передачи всех токенов не сделать фильтрации стоп-слов.. Да, наверное, лучше весь слайс передавать

2020-04-30 14:25 UTC, senyasdt reviewed
по соглашениям в *confluens* папка **filters** и всё содержимое из **cmd** должна переехать либо в **internal** либо в **pkg**. Смотри [тут](https://github.com/golang-standards/project-layout). Мне кажется что правильно было бы **filters** переместить в **pfg**.

2020-04-30 14:25 UTC, senyast4745 commented on cmd/filters/devision/devision.go
> +			return !unicode.IsLetter(r) && !unicode.IsNumber(r)
такая обратока не создаст проблем с чем то типу **can't**, которй превратится в `["can","t"]`?

2020-04-30 14:25 UTC, senyast4745 commented on cmd/filters/stopwords/stopwords.go
> +		if !stopwords.IsStopWord(strings.ToLower(token)) {
[Такая](https://github.com/bbalet/stopwords) (bbalet/stopwords) штука выглядит перспективнее.

2020-04-30 14:29 UTC, senyast4745 commented
> > Просто apply фильтра к каждому слову... Не знаю
> 
>  я просто хотел уйти от цикла в каждом фильтре. 

@K1ta, просто по моему такая сигнатура более правильная для фильтра к тексту. Можно же что то приколное намутить напрмер с весом и так далее, когда тебе нужен контекст

2020-04-30 14:40 UTC, senyast4745 commented
> Мне кажется, у тебя как то слишком сильно на модули разбито

Про слишком глубокую структуру папок и сильное разбиение фильтров тоже согласен

2020-04-30 15:06 UTC, AnBrusn reviewed
Тоже соглашусь, что лучше сделать интерфейс для фильтров и переделать структуру папок.

2020-04-30 16:44 UTC, TarIvAl commented on cmd/filters/devision/devision.go
> +			return !unicode.IsLetter(r) && !unicode.IsNumber(r)
такого не возникнет

2020-05-01 07:37 UTC, senyasdt requested changes
Изменения посмотрел. Основной вопрос как раз сейчас по самим фильтрам-функциям. По этому вопросу мне так же интересно мнение @K1ta. В остальном я согласен

2020-05-01 07:37 UTC, senyast4745 commented on pkg/filters/filters.go
> +		if !stopwords.IsStopWord(strings.ToLower(token)) {
bbalet/stopwords не понравился?

2020-05-01 07:37 UTC, senyast4745 commented on pkg/filters/filters.go
> +type Filter interface {
@K1ta я так подумал, посмотрел. Может лучше провернуть что то такое? 
```go
type Handler func(tokens []string) []string

func FilterText(text string, handlers ...Handler) []string{
...
    for _, handler := range handlers {
	tokens = handler(tokens)
    }
}
```
Просто это поможет не плодить кучу бесполезных структур

2020-05-01 07:37 UTC, senyast4745 commented on pkg/filters/filters.go
> +	"github.com/kljensen/snowball/english"
Просто из интереса, почему этот пакет, а не тот что был?

2020-05-01 09:39 UTC, TarIvAl commented on pkg/filters/filters.go
> +		if !stopwords.IsStopWord(strings.ToLower(token)) {
Ещё не дошел до него

2020-05-01 09:42 UTC, TarIvAl commented on pkg/filters/filters.go
> +	"github.com/kljensen/snowball/english"
Этот пакет мне больше понравился, но тот я использовал чтобы стемминг не применял нижний регистр, но в итоге он заработал не корректно и я вернулся к этому

2020-05-01 13:48 UTC, TarIvAl commented on pkg/filters/filters.go
> +type Filter interface {
согласен, сделал так

2020-05-01 13:57 UTC, TarIvAl commented on pkg/filters/filters.go
> +		if !stopwords.IsStopWord(strings.ToLower(token)) {
она лучше подходит для строк как я понимаю, а у нас обрабатываются токены отдельно. Предлагаю оставить то что сейчас

2020-05-02 08:21 UTC, senyast4745 commented on pkg/filters/filters.go
> +		if !stopwords.IsStopWord(strings.ToLower(token)) {
Хорошо

2020-05-02 08:21 UTC, senyast4745 commented on pkg/filters/filters.go
> +	"github.com/kljensen/snowball/english"
Хорошо

2020-05-02 09:58 UTC, K1ta commented on pkg/filters/filters.go
> +	var output []string
Думаю, что тут и в ToLower можно указать длину сразу, через make(), так как она не поменяется

2020-05-02 09:59 UTC, K1ta commented on pkg/filters/filters.go
> +	var output []string
Даже не длину, а capacity, если через append делать

2020-05-02 17:12 UTC, TarIvAl commented on pkg/filters/filters.go
> +	var output []string
согласен, сделал

2020-05-03 11:23 UTC, senyasdt requested changes
С остальным в общем и целом согласен. Вмерджи локально мастер в свою ветку, чтобы merge конфликты решить локально и запушь. Про оптимальность и слайсы решай сам, но по моему в худшем случае это что то типа *O(n^2)*

2020-05-03 11:23 UTC, senyast4745 commented on pkg/filters/filters.go
> +			tokens = append(tokens[:i], tokens[i+1:]...)
Выглядит как не оптимально по времени. Проще по моему создать новый слайс и добавлять в него и будет выглядеть читабельнее

2020-05-04 17:35 UTC, K1ta commented
Предложения:

1.  Добавить новый тип фильтра, который работает с одним словом, чтобы для каждого фильтра не делать цикл. Вопрос только в том, когда прогонять эти фильтры - до или после фильтров, работающих со всем текстом. 

2. Объединить фильтр для стемминга и для ToLower в один фильтр, чтобы не делать лишних операций в фильтре стемминга

2020-05-05 18:50 UTC, merged