SE-15 rest api
polyse/database pull request #4
Opened 2020-05-09 10:12 UTC by TarIvAl

добавил 2 ручки в web
для этого использовал echo
работает валидация 
НО пока что на вставку принимается только один документ и в целом необходимо ревью, чтобы продолжать в правильном направлении

2020-05-10 14:59 UTC, senyasdt requested changes
Так то всё хорошо, просто больше кодстайл

2020-05-10 14:59 UTC, senyast4745 commented on internal/web/web.go
> +	e.GET("/healthcheck", handleHealthcheck)
тогда может /api/healthchech?

2020-05-10 14:59 UTC, senyast4745 commented on internal/web/web.go
> +	e.GET("/api/:collection/documents", handleSearch)
Если нет, то тогда можно сделать отдельную группу под API рекветы по типу
```go
g := e.Group("/api")
g.GET("/;collection/documents")...
```

2020-05-10 14:59 UTC, senyast4745 commented on internal/web/web.go
> +	log.Debug().Str("param collection", collection).Str("query q", request.Query).Str("query limit", limit).Msg("handleSearch run")
Наверное лучше по оформлению будет как то так
```go
log.Debug().
    Str(...).
    Str(...).
    ...
    Msg()

```

2020-05-10 14:59 UTC, senyast4745 commented on internal/web/web.go
> +	if len(limit) != 0 {
По моему не обязательный параметр + ты валидируешь его уже echo валидатором

2020-05-10 14:59 UTC, senyast4745 commented on internal/web/web.go
> +	if len(limit) != 0 {
Точнее ты точно валидируешь его валидатором, так что можно либо тут валидировать и дефолтное значение ему проставить -1 чтобы из базы всё возвращалось, либо отсавить валидацию на библиотеку. Просто тейчас ты запилил лимит, но не пагинацию. Пример пагинации: [тык](https://github.com/siredwin/go-echo-paginator/blob/master/main.go).

2020-05-10 14:59 UTC, senyast4745 commented on internal/web/web.go
> +		return Bad(c)
Мне кажется есть смысл запилить централизованную обработку ошибок, раз echo это предоставляет. Дока по error-handling: [тык](https://echo.labstack.com/guide/error-handling)

2020-05-10 14:59 UTC, senyast4745 commented on internal/web/web.go
> +		return err
Наверно либо возвращаем либо обрабатываем а то как то разношёрстно не кайф

2020-05-11 11:55 UTC, K1ta requested changes
Во всем согласен с @senyast4745, нужно точно допилить пагинацию и сделать нормальную обработку ошибок

2020-05-11 14:31 UTC, tariel-x commented on internal/web/web.go
> +	Limit int    `validate:"gt=0"`
Я думаю, тут больше подойдёт gte и значение по-умолчанию в случае 0.

2020-05-11 14:31 UTC, tariel-x commented on internal/web/web.go
> +	var document Document
`handleAddDocuments`, но документ для записи, судя по коду, принимается один.

2020-05-12 09:54 UTC, TarIvAl commented on internal/web/web.go
> +	log.Debug().Str("param collection", collection).Str("query q", request.Query).Str("query limit", limit).Msg("handleSearch run")
поправил

2020-05-12 09:57 UTC, TarIvAl commented on internal/web/web.go
> +	e.GET("/api/:collection/documents", handleSearch)
добавил

2020-05-12 10:58 UTC, TarIvAl commented on internal/web/web.go
> +	if len(limit) != 0 {
если убрать эту проверку то limit становится обязательным параметром

2020-05-12 11:37 UTC, TarIvAl commented on internal/web/web.go
> +		return Bad(c)
поменял Bad на кастомный обработчик ошибок

2020-05-12 11:55 UTC, TarIvAl commented on internal/web/web.go
> +		return err
согласен

2020-05-12 11:57 UTC, TarIvAl commented on internal/web/web.go
> +	var document Document
просто функция в будущем будет принимать несколько документов

2020-05-12 11:59 UTC, TarIvAl commented on internal/web/web.go
> +	Limit int    `validate:"gt=0"`
изменил на gte=1,
у меня вопрос: лимит обязательный параметр?
мой код предусматривает, что лимит может быть вообще не отправлен и поэтому все именно так сделано

2020-05-12 12:04 UTC, tariel-x commented on internal/web/web.go
> +	Limit int    `validate:"gt=0"`
Лимит должен быть не обязательным параметром. Мне кажется, логичным, что лимит устанавливать не надо, чтоб проще делать запрос. И логичным, что когда делаешь запрос, он выполняется с каким-то предустановленным лимитом, чтоб случайно не убить базу. А если ставишь лимит 100500, то сам виноват.

2020-05-12 16:02 UTC, senyasdt requested changes
Мне пока не нравится обработка ошибок а так всё супер

2020-05-12 16:02 UTC, senyast4745 commented on internal/web/web.go
> +	err = c.JSONBlob(http.StatusOK, encodedJSON)
Ты на все ошибки отвечаешь код 200, но в тексте Bad Request. Это по моему не совсем правильно. Можно наверное запилить вот так
```go
type WebError struct{
  err    error
  code int
  msg  string
}

func (w WebError) Error() string {
   return w.err.Error()
}

func WrapErrorToWeb(int code, err error) WebError {
    return WebError{code: code, err: err, msg: http.StatusText(code)}
}

func WrapErrorToWebWithMsg(int code, string msg, err error) WebErr {
    return WebErr{err: err, code: code, msg: msg}
}

func httpErrorHandler(err error, c echo.Context){
    log.Err(err).Msg("web exception")
    if we, ok := err.(WebErr); ok {
        errJson := c.JSONBlob(we.code, []byte(we.text))
    } else {
        errJson := c.JSONBlob(http.InternalServerError, []byte(http.StatusText(http.InternalServerError)))
    }
}
```

И каждую ошибку вылетающую заворачивать с тем кодом ошибки с которым нужно. Или вощвращать уже завёрнутую, но такая обработка упростит жизнь имхо. Потому что для 400\500 .... не кайф писать каждый раз обработчик. У нас же не только 400 могут лететь

2020-05-12 16:02 UTC, senyast4745 commented on internal/web/web.go
> +	if len(limit) != 0 {
мы обсуждали пагинацию. Если запилишь, будет кайф

2020-05-12 16:09 UTC, senyasdt requested changes

2020-05-12 16:09 UTC, senyast4745 commented on internal/web/web.go
> +	if len(limit) != 0 {
Если ты сделаешь `gte=0`, то лимит перестаёт быть обязательным параметром. У него будет значение по умолчанию 0. По моему это нормальное поведение. Тип в sql лимит тоже не обязательный и если ты уронил базу - сам дурак

2020-05-12 16:10 UTC, senyast4745 commented on internal/web/web.go
> +	Limit int    `validate:"gt=0"`
В том же sql нет предустановленного лимита. И я не знаю насколько нужно делать нам предустановленный лимит

2020-05-12 16:10 UTC, senyast4745 commented on internal/web/web.go
> +	Limit int    `validate:"gt=0"`
Просто если сделать `gte=0` по моему всем будет счастье

2020-05-12 16:11 UTC, senyast4745 commented on internal/web/web.go
> +	Limit int    `validate:"gt=0"`
Просто если есть лимит значит должен быть хотя бы offset

2020-05-12 16:48 UTC, TarIvAl commented on internal/web/web.go
> +	if len(limit) != 0 {
понял, сделал

2020-05-12 17:18 UTC, TarIvAl commented on internal/web/web.go
> +	Limit int    `validate:"gt=0"`
сделал gte=0, не знаю почему сразу не догадался

2020-05-12 19:08 UTC, tariel-x commented on internal/web/web.go
> +	Limit int    `validate:"gt=0"`
Но у нас не SQL. Если сама возможность лимита в принципе будет, то логично установить лимит по-умолчанию, чтоб нельзя было убить базу запросом, которому удовлетворяют большое количество документов.

2020-05-13 08:28 UTC, TarIvAl commented on internal/web/web.go
> +	err = c.JSONBlob(http.StatusOK, encodedJSON)
реализовал обработку ошибок в таком формате

2020-05-13 10:08 UTC, senyasdt requested changes

2020-05-13 10:08 UTC, senyasdt commented on internal/web/web.go
> +	encodedJSON := []byte(`OK`)
Стоит навреное вмето просто **OK** сделать так же
```go
encodedMsg := []byte( http.StatusText(http.StatusOK))
```

2020-05-13 10:08 UTC, senyasdt commented on internal/web/web.go
> +	g.POST("/:collection/documents", handleAddDocuments)
Я не нашёл где ты для этих эндпоинтов устанавливаешь **Content-Type** для ответа. Просто сейчас он вроде как **application\json**, но по текстам ошибок и по тексту 200-ОК он **text\plain**

2020-05-13 10:08 UTC, senyasdt commented on internal/web/web.go
> +		errJSON = c.JSONBlob(http.StatusInternalServerError, []byte(http.StatusText(http.StatusInternalServerError)))
Из за того что мы вроде как хотим возвращать данные в **json**, а не просто текстом, то наверное следует сдеалть как то так
```go
var jsonFmt = "{\"msg\" : \"%s\"}"
...
errJson = c.JSONBlob(we.code, []byse(fmt.Sprintf(jsonFmt, we.msg))
...
errJson = c.JSONBlob(http.StatusInternalServerError, []byse(fmt.Sprintf(jsonFmt, http.StatusInternalServerError))
``` 

И то же самое проделать в `func ok()`

2020-05-13 10:08 UTC, senyasdt commented on internal/web/web.go
> +	encodedJSON := []byte(`OK`)
А ещё лучше как в комменте про ошибки)

2020-05-13 10:08 UTC, senyasdt commented on internal/web/web.go
> +}
Кажется что наследовние тут подойдёт лучше
```go
type Validator struct {
    validator.Validate
}

func (cv *Validator) Validate(i interface{}) error {
	return cv.Struct(i)
}
```

2020-05-13 10:08 UTC, senyast4745 commented on internal/web/web.go
> +func WrapWebError(code int, msg string, err error) WebError {
А зачем тут параметр `msg`? Выглядить unused

2020-05-13 10:08 UTC, senyast4745 commented on internal/web/web.go
> +func WrapWebError(code int, msg string, err error) WebError {
У меня он был чтобы кастомизировать msg ошибки. А тут ты на него просто забиваешь)

2020-05-13 10:08 UTC, senyast4745 commented on internal/web/web.go
> +		return WrapWebError(400, "Bad request.", err)
Вместо просто **400** лучше использовать `http.StatusBadRequest`

2020-05-13 10:08 UTC, senyast4745 commented on internal/web/web.go
> +	request.Offset, _ = strconv.Atoi(c.QueryParam("offset"))
Тебе не страшно так игнорировать ошибки?) Потому что в случае чего ты о них никогда не узнаешь

2020-05-13 10:52 UTC, TarIvAl commented on internal/web/web.go
> +	g.POST("/:collection/documents", handleAddDocuments)
JSONBlob отправляет как application\json

2020-05-13 10:54 UTC, senyast4745 commented on internal/web/web.go
> +	g.POST("/:collection/documents", handleAddDocuments)
Хорошо, но текст ошибок\ ответов пока что **text\plain** насколько я вижу

2020-05-13 11:04 UTC, TarIvAl commented on internal/web/web.go
> +	encodedJSON := []byte(`OK`)
сделал

2020-05-13 11:05 UTC, TarIvAl commented on internal/web/web.go
> +		errJSON = c.JSONBlob(http.StatusInternalServerError, []byte(http.StatusText(http.StatusInternalServerError)))
согласен, сделал так

2020-05-13 11:05 UTC, TarIvAl commented on internal/web/web.go
> +func WrapWebError(code int, msg string, err error) WebError {
убрал здесь msg

2020-05-13 11:05 UTC, TarIvAl commented on internal/web/web.go
> +		return WrapWebError(400, "Bad request.", err)
поменял

2020-05-13 11:16 UTC, TarIvAl commented on internal/web/web.go
> +	request.Offset, _ = strconv.Atoi(c.QueryParam("offset"))
если возникнет ошибка, то просто возьмется значение по умолчанию, а ошибка может быть только в случае некорректных входных данных, которые будут просто игнорироваться.

Могу сделать log.Error или log.Debug в случае ошибки, но не уверен, что он нужен, потому что ошибка будет возникать в каждый раз когда какой то из параметров не будет отправлен

2020-05-13 11:19 UTC, TarIvAl commented on internal/web/web.go
> +	request.Offset, _ = strconv.Atoi(c.QueryParam("offset"))
переделал, посмотри

2020-05-13 11:32 UTC, senyast4745 commented on internal/web/web.go
> +	request.Offset, _ = strconv.Atoi(c.QueryParam("offset"))
Хорошо, с этим согласен

2020-05-13 11:37 UTC, senyasdt requested changes
Меня всё устраивает кроме того, что я оставил в комментах. Ждём @tariel-x и так то можно мерджить

2020-05-13 11:37 UTC, senyast4745 commented on internal/web/web.go
> +		errJSON = c.JSONBlob(we.code, []byte(fmt.Sprintf(`{"message": "%d %s"}`, we.code, we.msg)))
можно вынести в блок var и переиспользвать. Как то так нпример 
```go
var (
 SimpleMessage = {"message": "%d %s"}
)
```

2020-05-13 11:46 UTC, senyasdt requested changes

2020-05-13 11:46 UTC, senyast4745 commented on internal/web/web.go
> +	// "github.com/polyse/databaseinternal/collection"
Никита расстроится увидев лишние импорты)

2020-05-13 11:46 UTC, senyast4745 commented on internal/web/web.go
> +	if err = c.Validate(request); err != nil {
К вопросу про наследование **Validate**

2020-05-13 11:48 UTC, TarIvAl commented on internal/web/web.go
> +}
так не будет работать, потому что Validate становится полем структуры и методом.
Возникает ошибка: `Validator.Validate is a field, not a method`

2020-05-13 11:52 UTC, TarIvAl commented on internal/web/web.go
> +	// "github.com/polyse/databaseinternal/collection"
я хотел в рамках этого задания добавить функцию вставки в бд из твоего пр

2020-05-13 12:00 UTC, TarIvAl commented on internal/web/web.go
> +		errJSON = c.JSONBlob(we.code, []byte(fmt.Sprintf(`{"message": "%d %s"}`, we.code, we.msg)))
добавил

2020-05-13 13:13 UTC, senyast4745 commented on internal/web/web.go
> +}
А метод `Validate()` нельзя переиметовать?
По моему завестись должно

2020-05-13 13:13 UTC, senyasdt requested changes
Так то я согласен со всем кроме валидации. Отсавил коммент выше. А так да, всё круто. Если считаешь что так валидировать будет правильно, тогда разрезолвь все мои заметки)

2020-05-13 22:57 UTC, tariel-x commented on internal/web/web.go
> +	err = c.JSONBlob(http.StatusOK, encodedJSON)
Тут используется `JSONBlob`, но текст ошибки передаётся ведь не в json.

2020-05-13 23:46 UTC, tariel-x requested changes

2020-05-13 23:46 UTC, tariel-x commented on internal/web/web.go
> +		Handler: e,
Не понятно, почему так? В echo же уже есть сервер, который можно вызывать. Мне кажется логичней хранить сразу объект echo, как здесь https://github.com/polyse/web-scraper/blob/master/internal/api/api.go#L14 и все миддлваре и прочее на него навешивать.

2020-05-13 23:46 UTC, tariel-x commented on internal/web/web.go
> +	log.Debug().Msg("handleHealthcheck run")
Не нужен здесь лог, healthcheck как правило мониторингом периодически вызывается и здесь будет только засорять логи.

2020-05-13 23:46 UTC, tariel-x commented on internal/web/web.go
> +		log.Debug().Err(err).Msg("can't convert limit to int")
Некорректные пользовательские параметры: вернуть 400 Bad request, чтоб пользователю сразу было всё понятно.

2020-05-13 23:46 UTC, tariel-x commented on internal/web/web.go
> +	e.GET("/healthcheck", handleHealthcheck)
API скорее всего будет обладать какой-то ссылкой на коллекцию или менеджер коллекций, поэтому эти функции сразу слеудует встроить в структуру App, которую, кстати, лучше бы переименовать в API.

2020-05-13 23:46 UTC, tariel-x commented on internal/web/web.go
> +func logMiddleware() echo.MiddlewareFunc {
У такого логгера по сравнению со стандартным `middleware.Logger()` есть недостаток - он не выводит код ответа, на которые часто смотрит всякий мониторинг. Если много 500 - сигнал тревоги.
Но стандартный логгер echo не подчиняется уровням логирования. 
Поэтому можно написать что-то среднее. И, кстати, duration тут некорректно вычислится.

2020-05-13 23:46 UTC, tariel-x commented on internal/web/web.go
> +func httpErrorHandler(err error, c echo.Context) {
Что-то я не очень понял, чем `echo.NewHTTPError(http.StatusUnauthorized, "Please provide valid credentials")` не угодил.

2020-05-13 23:46 UTC, tariel-x commented on internal/web/web.go
> +	request.Limit, err = strconv.Atoi(c.QueryParam("limit"))
если что, можно в 3 строки:
```golang
if request.Limit, err = strconv.Atoi(c.QueryParam("limit")); err != nil {
		log.Debug().Err(err).Msg("can't convert limit to int")
	}
```

2020-05-13 23:46 UTC, tariel-x commented on internal/web/web.go
> +	request.Query = c.QueryParam("q")
Можно тогда уж так, всё равно рефлексию используем.

```golang
type SearchRequest struct {
	Query  string `validate:"required" query:"name"`
	Limit  int    `validate:"gte=0"`
	Offset int    `validate:"gte=0"`
}
```
```golang
req := &SearchRequest{}
if err = c.Bind(u); err != nil {
    return
}
  ```

2020-05-13 23:47 UTC, senyast4745 commented on internal/web/web.go
> +	err = c.JSONBlob(http.StatusOK, encodedJSON)
Было изменено, стало в json формате

2020-05-14 02:02 UTC, senyast4745 commented on internal/web/web.go
> +func logMiddleware() echo.MiddlewareFunc {
А нельзя это как то сделать средствами zerolog?

2020-05-14 02:03 UTC, senyast4745 commented on internal/web/web.go
> +func httpErrorHandler(err error, c echo.Context) {
Просто я его не заметил)

2020-05-14 02:05 UTC, senyast4745 commented on internal/web/web.go
> +func logMiddleware() echo.MiddlewareFunc {
В смысле достать код ответа.

2020-05-14 14:02 UTC, TarIvAl commented on internal/web/web.go
> +func httpErrorHandler(err error, c echo.Context) {
и я не заметил) 
заменил на него

2020-05-14 14:03 UTC, TarIvAl commented on internal/web/web.go
> +		Handler: e,
сделал как в пауке

2020-05-14 14:03 UTC, TarIvAl commented on internal/web/web.go
> +	log.Debug().Msg("handleHealthcheck run")
убрал

2020-05-14 14:08 UTC, TarIvAl commented on internal/web/web.go
> +		log.Debug().Err(err).Msg("can't convert limit to int")
ошибки возникают в том числе когда лимит или оффсет отправлены не были и если ошибки обрабатывать параметры станут обязательными, поэтому сейчас именно так

2020-05-14 14:38 UTC, TarIvAl commented on internal/web/web.go
> +	request.Query = c.QueryParam("q")
сделал так

2020-05-14 17:33 UTC, TarIvAl commented on internal/web/web.go
> +	e.GET("/healthcheck", handleHealthcheck)
согласен, сделал

2020-05-14 17:44 UTC, TarIvAl commented on internal/web/web.go
> +func logMiddleware() echo.MiddlewareFunc {
не совсем понимаю, что имеется ввиду под чем то средним (

2020-05-14 21:56 UTC, tariel-x commented on internal/web/web.go
> +func logMiddleware() echo.MiddlewareFunc {
https://github.com/polyse/template/pull/2/files#diff-1c93640aec056ac956d6bd96ee83a3c8R48
как-то так

2020-05-14 22:41 UTC, senyast4745 commented on internal/web/web.go
> +}
Не получилось?  Просто ради интереса?

2020-05-15 10:31 UTC, TarIvAl commented on internal/web/web.go
> +}
я пробовал переименовывать Validate(), у меня не получилось так избавиться от ошибок. Предлагаю оставить так как сейчас

2020-05-15 16:21 UTC, senyasdt commented on internal/web/web.go
> +		log.Debug().Err(err).Msg("")
Наверное не стоит оставлять msg пустыми. А то не очень ясно откуда она вылетела и причем она вообще

2020-05-15 16:21 UTC, senyasdt commented on internal/web/web.go
>  	log.Info().Msg("database server started")
Можно ещё интерфейс который база данных слушает вывести

2020-05-15 16:21 UTC, senyasdt commented on internal/web/web.go
> +			// Int("status", c.Response().Status).
А что тут не пошло?

2020-05-15 16:21 UTC, senyasdt commented on internal/web/web.go
> +		// middleware.Logger()(next)
Лишние комменты

2020-05-15 18:09 UTC, TarIvAl commented on internal/web/web.go
>  	log.Info().Msg("database server started")
echo Start уже выводит

2020-05-15 18:16 UTC, TarIvAl commented on internal/web/web.go
> +			// Int("status", c.Response().Status).
этого уже нет, не знаю почему все еще показывает

2020-05-15 18:24 UTC, TarIvAl commented on internal/web/web.go
> +		log.Debug().Err(err).Msg("")
согласен, добавил

2020-05-16 11:55 UTC, tariel-x commented on internal/api/api.go
> +	return ok(c)
Как правило, различные REST API возвращают вставленные документы вместе с их сгенерированными при вставке ID. У нас ID пока нет (вроде как оригиналы документов никуда не сохраняются), поэтому пока стоит возвращать просто вставленные документы.

2020-05-16 11:56 UTC, tariel-x commented on internal/api/api.go
> +	return ok(c)
@senyast4745 , обрати внимание тоже на этот момент

2020-05-16 12:35 UTC, tariel-x commented on internal/api/api.go
> +	return ok(c)
И ещё, в случае успешной вставки, можно будет вернуть вставленные документы, статуст 201 created и никакого дополнительного message имхо возвращать не надо.

2020-05-16 12:37 UTC, tariel-x commented on internal/api/api.go
> +	// here will be sending document to bd
Вставка уже реализована, можно уже заиспользовать тут.

2020-05-16 12:53 UTC, senyast4745 commented on internal/api/api.go
> +	return ok(c)
Хорошо, допишу

2020-05-17 18:30 UTC, senyasdt approved these changes

2020-05-17 22:07 UTC, tariel-x commented on internal/api/api.go
> +	return c.JSON(http.StatusCreated, http.StatusText(http.StatusCreated))
Давайте тут уже сейчас вернём вставленные документы: хотя бы просто распарсенные docs

2020-05-18 12:11 UTC, TarIvAl commented on internal/api/api.go
> +	return c.JSON(http.StatusCreated, http.StatusText(http.StatusCreated))
сделал пока что так

2020-05-18 12:12 UTC, tariel-x approved these changes

2020-05-18 12:16 UTC, merged